### ISSUE TITLE
Unhandled Exception: eazdevirt.MethodStubNotFoundException: Exception of type 'e azdevirt.MethodStubNotFoundException' was thrown.

### ISSUE THREAD

**Issue by AxDSan** [saneki/eazdevirt#3]
It pop ups every time I try to devirtualize a dll.

![Image of Error](http://i.imgur.com/8nHfvRt.png)

Any help is deeply appeciated!

**Comment by saneki** [comment]
Are you sure the .dll is virtualized? Also, have you deobfuscated the control flow before running eazdevirt: `de4dot --dont-rename --keep-types --preserve-tokens MyAssembly.dll`

If it's virtualized and control-flow deobfuscated and eazdevirt still isn't working, could you upload the .dll so I could look at it?
